---
- name: Install datahugger and download dataset
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure python3 and pip3 are installed
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install datahugger Python module
      ansible.builtin.pip:
        name: datahugger
        state: present
        executable: pip3

    - name: Download the dataset
      grycap.dataset.download_dataset:
        dataset_url: "{{ dataset_url }}"
        output_dir: "{{ output_dir }}"
